### ISSUE TITLE
Cannot start pyrespeeder_gui.py

### ISSUE THREAD

**Issue by Efenstor** [HENDRIX-ZT2/pyaudiorestoration#13]
I'm on Debian 10. I've installed most of the modules from pip. Still getting this when trying to execute _python3 pyrespeeder_cmd.py_:
```
Traceback (most recent call last):
  File "pyrespeeder_gui.py", line 213, in <module>
    widgets.startup( MainWindow )
  File "/home/olaf/bin/pyaudiorestoration/util/widgets.py", line 19, in startup
    win = cls()
  File "pyrespeeder_gui.py", line 13, in __init__
    widgets.MainWindow.__init__(self, "pyrespeeder", widgets.ParamWidget, Canvas, 1)
  File "/home/olaf/bin/pyaudiorestoration/util/widgets.py", line 565, in __init__
    self.canvas = canvas_widget(parent=self)
  File "pyrespeeder_gui.py", line 36, in __init__
    spectrum.SpectrumCanvas.__init__(self, spectra_colors=(None,), y_axis='Octaves' )
  File "/home/olaf/bin/pyaudiorestoration/util/spectrum.py", line 213, in __init__
    self.spec_yaxis = vispy_ext.ExtAxisWidget(orientation='left', axis_label='Hz', axis_font_size=8, axis_label_margin=35, tick_label_margin=5, scale_type="logarithmic")
  File "/home/olaf/bin/pyaudiorestoration/util/vispy_ext.py", line 216, in __init__
    self.axis = ExtAxisVisual(**kwargs)
  File "/home/olaf/bin/pyaudiorestoration/util/vispy_ext.py", line 251, in __init__
    self.axis_color = axis_color
  File "/usr/local/lib/python3.7/dist-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/usr/local/lib/python3.7/dist-packages/vispy/visuals/axis.py", line 143, in axis_color
    self._line.set_data(color=value)
AttributeError: 'ExtAxisVisual' object has no attribute '_line'
```
Some module version mismatch?

**Comment by HENDRIX-ZT2** [comment]
This may be due to recent vispy updates. Try:
pip install vispy==0.5.3

**Comment by Efenstor** [comment]
> This may be due to recent vispy updates. Try:
> pip install vispy==0.5.3

It worked! Thanks a lot.

Great software by the way. I've been looking for any open-source alternative to Capstan and it seems I've actually found one! Keep your work, it's really worth it!

**Comment by HENDRIX-ZT2** [comment]
Cool! Good luck!
If used properly, it easily beats capstan in accuracy - it only lacks an automatic mode.
