### ISSUE TITLE
No Waveforms in Gui - Windows 10 - Run from pycharm after issues installing from cmd

### ISSUE THREAD

**Issue by MrShinyBoots** [HENDRIX-ZT2/pyaudiorestoration#24]
hi there i have installed all requirements and have got setup.py to finally work after using Pycharm virtual env as a work around (another issue to do with windows/appdata acess levels not allowing changes..

but i still have no waveforms appearing in the gui? 

I am reading this set of errors when I run which i assume is something to do with the lack of waveforms? - but I am unsure how to fix them? - i am a bit of a programming noob i'm afraid and required help just to get to this step

WARNING: Traceback (most recent call last):
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\pyaudiorestoration\pyrespeeder_gui.py", line 265, in <module>
    widgets.startup(MainWindow)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\pyaudiorestoration\util\widgets.py", line 31, in startup
    win.show()
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\app\backends\_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\app\backends\_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\app\backends\_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\scene\canvas.py", line 218, in on_draw
    self._draw_scene()
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\scene\canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\scene\canvas.py", line 315, in draw_visual
    node.draw()
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\scene\visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\visuals\visual.py", line 605, in draw
    v.draw()
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\visuals\visual.py", line 600, in draw
    if self._prepare_draw(view=self) is False:
  File "C:\Program Files\pyrestoration\pyaudiorestoration-master\venv\lib\site-packages\vispy\visuals\axis.py", line 257, in _prepare_draw
    self._axis_label_vis.rotation = self._rotation_angle
AttributeError: 'ExtAxisVisual' object has no attribute '_axis_label_vis'
ERROR: Invoking <bound method SceneCanvas.on_draw of <Canvas (PyQt5) at 0x2ad412e0e50>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <Canvas (PyQt5) at 0x2ad412e0e50>> repeat 2
ERROR: Invoking <bound method SceneCanvas.on_draw of <Canvas (PyQt5) at 0x2ad412e0e50>> repeat 4

any help would be useful - many thanks

**Comment by fcfalmeida** [comment]
I'm getting the exact same error on MacOS Monterey 12.0.1 using Python 3.6. I've installed all required dependencies. No waveforms appear on GUI. Any help would be appreciated.

**Comment by HENDRIX-ZT2** [comment]
This sounds like you have the current version of vispy installed. You'll likely need an older version as specified in setup.py

**Comment by fcfalmeida** [comment]
> This sounds like you have the current version of vispy installed. You'll likely need an older version as specified in setup.py

Completely forgot to check `setup.py`. Installed vispy 0.6.4 instead and it appears to be working now. Thank you so much!

**Comment by damian238** [comment]
Same problem on windows 10. Tried and failed to install vispy 0.6.4 
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Numpy: 1.22.2
Vispy: 0.12.1

**Comment by damian238** [comment]
I'm kind of desperate to get this working. I'd made some tapes of my guitar playing 40 years ago and not one of them is without extreme wow and flutter. I can not remake them so it's all that's left of my tears of playing. Before now there was nothing I could afford to fix them. What can I do?

**Comment by damian238** [comment]
I can't help but think that the negative value referenced in bold at the end here might be a clue as to how things have gone wrong here...
Reading C:/guitar music/Track01.wav
storing new fft ('C:/guitar music/Track01.wav', 2048, 0, 512)
Reading speed data
Reading regression data
Retrieving FFT from processing thread
ERROR: Invoking <bound method SceneCanvas.on_draw of <Canvas (PyQt5) at 0x2bdbe8e10a0>> repeat 128
WARNING: Traceback (most recent call last):WARNING: Traceback (most recent call last):
  File "C:\Damian\flutterFix\pyaudiorestoration-master\pyaudiorestoration\pyrespeeder_gui.py", line 265, in <module>
    widgets.startup(MainWindow)
  File "C:\Damian\flutterFix\pyaudiorestoration-master\pyaudiorestoration\util\widgets.py", line 32, in startup
    appQt.exec_()
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\app\backends\_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\app\backends\_qt.py", line 512, in mouseReleaseEvent
    self._vispy_mouse_release(
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\app\base.py", line 224, in _vispy_mouse_release
    ev = self._vispy_canvas.events.mouse_release(**kwargs)
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\Damian\flutterFix\pyaudiorestoration-master\pyaudiorestoration\pyrespeeder_gui.py", line 233, in on_mouse_release
    track = wow_detection.Track(
  File "C:\Damian\flutterFix\pyaudiorestoration-master\pyaudiorestoration\util\wow_detection.py", line 43, in __init__
    self.sample_trail(trail)
  File "C:\Damian\flutterFix\pyaudiorestoration-master\pyaudiorestoration\util\wow_detection.py", line 75, in sample_trail
    self.times = np.linspace(self.frame_0*self.hop/self.sr, self.frame_1*self.hop/self.sr, self.frame_1-self.frame_0)
  File "<__array_function__ internals>", line 180, in linspace
  File "C:\Users\Damian\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\function_base.py", line 122, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
**ValueError: Number of samples, -10692, must be non-negative.**
ERROR: Invoking <bound method Canvas.on_mouse_release of <Canvas (PyQt5) at 0x2bdbe8e10a0>> for MouseEvent

This occurred when I tried to select in the spectral window (despite nothing being visible).

**Comment by HENDRIX-ZT2** [comment]
However, I have improved the installation instructions to be more up to date and removed my code's requirements for specific older dependencies' versions. So please test the installation again with the current code and instructions.
