### ISSUE TITLE
[HELP] Installation problems (Windows/Linux)

### ISSUE THREAD

**Issue by forart** [HENDRIX-ZT2/pyaudiorestoration#26]
Hi there, we would like to use the software to participate in an online restoration / declip competition finally, although we have followed all the instructions, we have not been able to make it work either on Windows or - even worst - on Linux.

Is it possible to implement a step-by-step guide (including all needed - working - components download links) to make it run?

Thanks in advance.

note: we strongly suggest you to check out other Python-based projects (such as @cdgriffith 's [FastFlix](https://github.com/cdgriffith/FastFlix)) to get an "inspiration" on how it should be released for different platforms.

Hope that inspires.

**Comment by davidhealey** [comment]
@forart Did you ever manage to get up and running? I've been trying on Debian and Windows here with no success.

**Comment by HENDRIX-ZT2** [comment]
I have improved the installation instructions to be more up to date and removed my code's requirements for specific older dependencies' versions. So please test the installation again with the current code and instructions.

**Comment by davidhealey** [comment]
Oh thanks! I'll give it a try

**Comment by Bambam0304** [comment]
I need help it Keeps Spitting Out this Error
Collecting pyqt5 (from -r requirements.txt (line 1))
  Using cached PyQt5-5.15.11-cp38-abi3-win_amd64.whl.metadata (2.1 kB)
Collecting soundfile (from -r requirements.txt (line 2))
  Using cached soundfile-0.12.1-py2.py3-none-win_amd64.whl.metadata (14 kB)
Collecting matplotlib==2.2.5 (from -r requirements.txt (line 3))
  Using cached matplotlib-2.2.5.tar.gz (36.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      <string>:9: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
      <string>:24: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
      Traceback (most recent call last):
        File "C:\Users\peter\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\peter\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\peter\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-w2zqha8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-w2zqha8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-w2zqha8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\peter\AppData\Local\Temp\pip-build-env-w2zqha8d\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 44, in <module>
        File "C:\Users\peter\AppData\Local\Temp\pip-install-zvbvzck0\matplotlib_688a9a2e73ff4ac79630e70f079de8ca\versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ~~~~~~~~~~~~^^
        File "C:\Users\peter\AppData\Local\Temp\pip-install-zvbvzck0\matplotlib_688a9a2e73ff4ac79630e70f079de8ca\versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
        File "C:\Users\peter\AppData\Local\Temp\pip-install-zvbvzck0\matplotlib_688a9a2e73ff4ac79630e70f079de8ca\versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by HENDRIX-ZT2** [comment]
@Bambam0304 you're on python 3.13, make sure you use the version recommended in the instructions!

**Comment by Bambam0304** [comment]
Sorry I miss understood the instructions. But I guessed that that would be the problem.
